### ISSUE TITLE
redirect_uri_mismatch

### ISSUE THREAD

**Issue by tuxedojoe** [aellerton/demo-allauth-bootstrap#17]
Hi,
I really appreciate the idea and the work you guys are doing with this project! Seriously, your project here is why I now officially love Django.

But, I ran into a problem today. Installed everything from scratch will the beautiful and easy install make files and all. But I can't seem to get my google callback URI to work:

Error: redirect_uri_mismatch

The redirect URI in the request, http://localhost:8000/accounts/google/login/callback/, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/

Am I doing anything wrong? Have looked through your walkhrough over and over again. Almost seems like a bug, since I haven't changed anything in the demo.

**Comment by aellerton** [comment]
Thanks for the nice words :)

Getting the URIs right can be annoying. Facebook is even worse than Google, but I updated the instructions recently and hopefully it's a bit clearer.

It's almost certainly your Google credentials set up and not a bug. Usually when this happens to me it's that the Facebook/Google credentials aren't set up right, or the UI labels are misleading (Facebook).

Steps to check something like...

1. Are you definitely serving the site on ``http://localhost:8000`` ?
2. In your Google credentials configuration does "authorised javascript origin" definitely include ``http://127.0.0.1:8000`` ?
3. On the same screen does "authorised redirect URIs" definitely include ``http://127.0.0.1:8000/accounts/google/login/callback/`` ?

**Comment by tuxedojoe** [comment]
Wow! That was a quick response! Thanks!

I've doublechecked the Google credentials thrice now so, they are correct. However, you write in _1) Are you definitely serving the site on http://localhost:8000 ?_

It seems when I run "make run" that the server is at http://127.0.0.1:8000 but that shouldn't be a problem right?

But, when I want to launch the demo not using make, using "python manage.py runserver 127.0.0.1:8000" i get import errors: "No module named 'bootstrap3'.

Can that have something to do with it?

**Comment by tuxedojoe** [comment]
Hurray! Running the website from http://127.0.0.1:8000 instead of http://localhost:8000 in the browser solved it!

Thanks for leading me in the right direction. Might add that it tips for the google login instructions as well.

Again, awesome work! And thanks for the quick response!

**Comment by aellerton** [comment]
Excellent!

I've updated the README to make this more clear - hopefully anyway.

I don't know why you got the ``No module named bootstrap3`` error. That implies you're running a version of Python without that module installed, but it wouldn't work from ``make run`` if that were the case. Anyway, sounds like that isn't a problem any more.

**Comment by Hritik01** [comment]
I tried both http://127.0.0.1:8000/ and http://localhost:8000/ in my javascript origins. I am still getting the redirect_url_mismatch error.
Please help.

**Comment by aellerton** [comment]
Did you follow all the other instructions? Can you post the exact error, or
screenshot?
